# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 244bdf09c4ac3d0915ece88eb812b5afda5a53342dc324b8bdc34febcde656d23ca57a82eba1d3c2574a6b4f363814b8624ccfe346ea7690c0546da7e8fdca64

test:
  secret_key_base: 63ee597b8fa1ab3b7f22e3a2b676f42aad1ff89f118cf82070f3887097c4e78048091ad493f6961967a0c4cfd221734676f5b93acffcc14fc8905092f9fdd8d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
